### ISSUE TITLE
Missing assembly reference

### ISSUE THREAD

**Issue by S3cur3Th1sSh1t** [nccgroup/WMIcmd#2]
Hi,

i tried to build the Code with VS Community and xbuild now. Both times the CommandLine and IPParserState references are not found.

Options.cs(15,7): error CS0246: The type or namespace name `CommandLine' could not be found. Are you missing an assembly reference?
        Options.cs(16,7): error CS0246: The type or namespace name `CommandLine' could not be found. Are you missing an assembly reference?
        Options.cs(53,16): error CS0246: The type or namespace name `IParserState' could not be found. Are you missing an assembly reference?

I didnt know which .dll to reference to. Some help? :)

Greetings

**Comment by olliencc** [comment]
So if you open in the GUI and resolve the NuGet dependencies you should be fine. You need - https://commandline.codeplex.com

This has been tested with VS Community 2017.

**Comment by S3cur3Th1sSh1t** [comment]
Quick help, thanks. I´ll try that.

**Comment by S3cur3Th1sSh1t** [comment]
It Works, thank you very much.
