### ISSUE TITLE
What is the difference between WMIcmd and wmic?

### ISSUE THREAD

**Issue by CaledoniaProject** [nccgroup/WMIcmd#3]
Hi there,

I'm wondering why you created this tool, is there any advantage over the `wmic` command?

**Comment by olliencc** [comment]
wmic allows you to script WMI including executing operating system commands.

per the readme this tool allows you to execute operating system commands and capture stdout (via the registry which itself is read via WMI) without redirecting to the file system and having to use SMB.

so in short this command allows you to have a close to cmd.exe like experience.
